### PR TITLE
Add defaultValue and initialValue

### PR DESCRIPTION
**Pull request by PerfectPixel**
Hey Erik,

today I needed to set an `initialValue` on the array, which led to a weird workaround for me. So here the PR:

I copied the explanation from the `react-final-form` repository, and also added the `defaultValue`.

I though about checking that the values are array but then decided against it. Maybe it would make sense to pass all the other props through too?

Cheers!

### CODE REVIEW

**Comment by PerfectPixel** [comment]
I noticed that using `initialValue` with `useFieldArray` leads to react constantly updating. Maybe you have an idea what causes it @erikras

**Comment by erikras** [comment]
Can you add these two to `index.d.ts`, too?

**Comment by PerfectPixel** [comment]
I could, but isn't that redundant as `UseFieldArrayConfig<FieldValue>` extends `UseFieldConfig<FieldValue>` and `UseFieldConfig` already contains `initialValue` and `defaultValue` 🤔

**Comment by PerfectPixel** [comment]
@erikras any decision on my question above? 🙃

**Comment by erikras** [comment]
Published in [`v3.1.1`](https://github.com/final-form/react-final-form-arrays/releases/tag/v3.1.1).

**Pull request merged**
