### PR TITLE
Fixed FieldArray re-render on every change when subscription is empty…

### LINKED ISSUE #93: FieldArray re-renders even if the subscription prop is set, the subscription prop is ignored
### What is the current behavior?
FieldArray re-renders on any Field event even when the FieldArray subscription={{}} prop is set, seems like the subscription prop is ignored. 
This happens when using react-final-form-arrays 3 and react-final-form 6
when I downgrade to react-final-form-arrays 2 and react-final-form 4 everything works as expected

### What is the expected behavior?
FieldArray should not re-render on Field change event when the subscription prop is set to {{}}

### Sandbox Link
[https://codesandbox.io/embed/react-final-form-field-arrays-mblll](https://codesandbox.io/embed/react-final-form-field-arrays-mblll)

### What's your environment?
```
{
    "final-form": "4.16.1",
    "final-form-arrays": "1.1.2",
    "react": "16.8.6",
    "react-dom": "16.8.6",
    "react-final-form": "6.3.0",
    "react-final-form-arrays": "3.1.0",
}
```
### Other information
Use the linked sandbox and see the console log comment that runs in the FieldArray component when the FieldArray re-renders on each key type in any FieldArray input. Than downgrade to react-final-form-arrays 2 and react-final-form 4 and the log will print only when the FieldArray mounts and not on every key press in the input field

### PR DESCRIPTION
**Pull request by jdimovska**
Hey,

This PR fixes #93
I created a test where we pass an empty subscription object to the FieldArray and we check if only the Field whose value has changed gets re-rendered. 
The test passes with this fix.

### CODE REVIEW

**Comment by erikras** [comment]
Seems like this is going to necessarily break the `value` API... #96

Well, I guess if you provide a `subscription` prop and don't include `value`, then you don't get the `value`...?

**Comment by oliverlaz** [comment]
Hi @erikras, Hi @jdimovska,

I had a look at the linked issue and the provided fix.
@erikras is right, with these changes, `value` subscription is disabled by default.

Maybe an alternative approach would be to let the defaults (`value`, `length`) be overridden by the `subscription` prop on `<FieldArray />`

```jsx
<FieldArray subscription={{ value: false }} />
```

In order this approach to work, [this code](https://github.com/final-form/react-final-form-arrays/blob/10ee4b929a92b9ef961c690276d61fdeda7f0dfd/src/useFieldArray.js#L60) should be changed from:
`subscription: { ...subscription, value: true, length: true },` to
`subscription: { value: true, length: true, ...subscription }`.

With this change, all existing tests together with the new one pass successfully.
This change should be backwards compatible and shouldn't cause any side-effects if this library is used as recommended. However, it would be good if it is mentioned in the docs.

What are your thoughts on this?

**Comment by SpearThruster** [comment]
Hi all,

`subscription={{}}` is definitely how `ReactFinalForm` interprets "no subscription" on the `Form` component. It makes sense for the same rule to apply here. 

This will help greatly with optimizing large form sections (represented with field arrays) which are unrelated to each other.

**Comment by erikras** [comment]
Published in [`v3.1.1`](https://github.com/final-form/react-final-form-arrays/releases/tag/v3.1.1).

**Pull request merged**
