### PR TITLE
[typescript] add tests and implementation for FieldArrayProps

### LINKED ISSUE #17: Typescript error for FieldArrayProps
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

**FieldArrayProps** is included from _final-form_ and throws an error
```
/node_modules/final-form/dist/index has no exported member 'FieldArrayProps'  
```

https://github.com/final-form/react-final-form-arrays/blob/32367dce89037cab1b79847ce8dd28522f87add4/src/index.d.ts#L2

### What is the expected behavior?

Should not throw Typescript exception, but it looks like FieldArrayProps does not exist in https://github.com/final-form/final-form/blob/master/src/index.d.ts

### PR DESCRIPTION
**Pull request by rosskevin**
Closes #17 

Depends on https://github.com/final-form/final-form-arrays/pull/8
Depends on https://github.com/final-form/react-final-form/pull/129

### CODE REVIEW

**Comment by rosskevin** [comment]
Once versions are bumped for https://github.com/final-form/final-form-arrays/pull/8 and  https://github.com/final-form/react-final-form/pull/129, this one will be good to go.

**Comment by erikras** [comment]
Doh! @rosskevin.

[`The script called "typescript" which runs "tsc" failed with exit code 1`](https://travis-ci.org/final-form/react-final-form-arrays/builds/332355297)

**Comment by rosskevin** [comment]
I'll check it out

**Comment by rosskevin** [comment]
This should have been fixed by my change to `react-final-form`.  `FormRenderProps.mutatators` should be defined, not undefined.  https://github.com/final-form/react-final-form/pull/129/files#diff-b739f95ace6bbf2f0fd5e8cf1dab97d8R47

Checking now to see what's the deal with the release.

**Comment by rosskevin** [comment]
@erikras react-final-form needs a release, then this needs bumped.

**Comment by rosskevin** [comment]
@erikras - I'm not sure why there are unrelated test failures.  If you can take a look, I would appreciate it.

On an unrelated note, I found more ts inaccuracies (here) - I'll work on that now, let's leave this open.

**Comment by rosskevin** [comment]
@erikras `FieldState` (e.g. `active | blur`) is being picked up in `...meta`, so either the runtime is wrong or the types are wrong.  where should `FieldState` be in the `FieldArrayRenderProps`?

**Comment by rosskevin** [comment]
Snapshot of FieldState mixed into render props:

fieldstate

**Comment by rosskevin** [comment]
@erikras I think all `FieldState` values should be moved under `fields`.  The types imply it already and I think that makes sense.  Should I make that change?

**Comment by erikras** [comment]
> Should I make that change?

mnee7

**Comment by rosskevin** [comment]
@erikras any ideas about the test failures?  https://travis-ci.org/final-form/react-final-form-arrays/builds/332369245

**Comment by erikras** [comment]
[Fixed it](https://github.com/final-form/react-final-form-arrays/pull/18/commits/c3c82e4da727cef3063676d98dd701415f48234d).

**Comment by rosskevin** [comment]
Great, thank you.  This one is good to merge/release

**Comment by erikras** [comment]
Published in [`v1.0.3`](https://github.com/final-form/react-final-form-arrays/releases/tag/v1.0.3).

**Pull request merged**
